const PRIMARY_COLOR = '#9F3E1A'
const SECONDARY_COLOR = '#496277'
const PRIMARY_ORANGE_COLOR = '#E7900F'
const PRIMARY_GREEN_COLOR = '#91B38B'

export {
  PRIMARY_COLOR,
  SECONDARY_COLOR,
  PRIMARY_ORANGE_COLOR,
  PRIMARY_GREEN_COLOR
}
